config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :projects do
    collection do
      post :sort
    end

    member do
      get :settings
      get :contributors
    end

    resources :stories do
      collection do
        post :sort
        get :new_import
        post :import
      end

      member do
        post :close
      end

      patch :assign, :set_state, on: :member
      resources :comments
      resources :attachments, only: :attach do
        post :attach, on: :collection
      end
    end

    resources :discussions do
      resources :comments
    end

    resources :contributions, only: [:create, :destroy] do
      member do
        post 'resend_invitation'
        patch 'update_initials'
        patch 'update_role'
      end
    end

    resources :attachments do
      member do
        post 'download'
      end
      resources :comments
    end

    resources :events do
      get :get_events, on: :collection
    end

    resources :integrations, except: [:new], param: :secure_id do
      member do
        get :new_import
        post :start_import
        match :accept_payload, defaults: {formats: :json}, via: [:post, :head] # Trello sending HEAD request
      end

      constraints name: /#{Integration::AVAILABLE_INTEGRATIONS.join('|')}/ do
        get '/:name' => 'integrations#new', on: :collection, as: :list
      end
    end
  end

  resources :notification_settings, only: [:index, :update]

  resources :contributions, only: :join do
    get :join, on: :member
  end

  devise_for :users, :controllers => {omniauth_callbacks: 'users/omniauth_callbacks', :registrations => 'users/registrations'}

  devise_scope :user do
    match '/users/:id/finish_signup', :to => 'omniauth_callbacks#finish_signup', via: [:get, :patch], :as => :finish_signup
    match '/users/:id/associate_account', :to => 'omniauth_callbacks#associate_account', via: :patch, :as => :associate_account
  end

  resources :notifications do
    collection do
      patch 'mark_all_read'
      patch 'clear_all'
    end
  end
  root 'welcome#index'
  get 'notifications' => 'notifications#index'

end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id              :integer          not null, primary key
#  receiver_id     :integer
#  performer_id    :integer
#  content         :json
#  notifiable_type :string
#  notifiable_id   :integer
#  read            :boolean          default(FALSE)
#  hidden          :boolean          default(FALSE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

# TODO: Rename to UserNotification
class Notification < ApplicationRecord
  belongs_to :receiver, class_name: 'User'
  belongs_to :performer, class_name: 'User' # We can use it while updating i-e if user changes his name
  belongs_to :notifiable, polymorphic: true


  default_scope { where(hidden: [false, nil]) }

  validates :receiver, presence: true

  # To create shortcut methods like notification.performer_name instead of notification.content['performer_name']
  store_accessor :content, [:performer_name, :text, :action, :resource_id, :resource_type, :resource_fid, :resource_link, :project_fid]

  default_scope { where(hidden: [false, nil]) }

  scope :unread, -> { where(read: false) }

  # utility method that returns action like 'Created Story'
  # For now combining action with type, we can customize it i-e instead of 'Created Comment' return 'commented'
  def resource_action
    [action, resource_type].join(' ')
  end

  def comment?
    self.notifiable_type == 'Comment'
  end

  def send_faye_notifications
    message = [performer_name, resource_action, text].join(' ')

    begin
      PrivatePub.publish_to('/messages/private/user'+ receiver.to_s, message: message)
    rescue => ex
      logger.error ex.message
    end
  end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:update, :destroy]

  def index
    @notifications = Notification.where(receiver: current_user).order("created_at desc")
    @page = params[:page].try(:to_i) || 1

    respond_to do |format|
      # TODO: Delete this line and views/notifications/old_index_grouped.html.erb template
      # format.html { @notifications = @notifications.group_by { |n| n.story_or_discussion } }
      format.html { @notifications = @notifications.unscoped.paginate(page: @page, :per_page => 30) }
      format.js { @notifications = @notifications.paginate(:page => @page, :per_page => 10) }
    end
  end

  # this is used for marking a notifications as read
  def update
    respond_to do |format|
      format.json {

        # on successful update we decrease notification count from views using js
        # making sure that notification is unread before updating it
        # An other option is that we can calculate unread count on server side and sent it back with with response
        if !@notification.read? && @notification.update_attributes(read: true)
          render json: {}, status: :ok
        else
          render json: @notification.errors, status: :unprocessable_entity
        end
      }
    end
  end

  def mark_all_read
    respond_to do |format|
      format.js {
        current_user.notifications.update_all(read: true)
      }
    end
  end

  def clear_all
    respond_to do |format|
      format.js {
        # TODO: Update views only if this query is successful
        current_user.notifications.update_all(hidden: true)
      }
    end
  end

  def destroy
    if @notification.update_attributes(hidden: true)
      render json: {}, status: :ok
    else
      render json: {status: 'Not Deleted'}, status: :unprocessable_entity
    end
  end

  private
  def set_notification
    @notification = Notification.find(params[:id])
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def main_link(notification)
    link_text = notification.resource_fid || notification.project_fid # append ID with project_fid? for discussions
    content_tag :span do
      link_to(link_text, notification.resource_link, class: 'text-uppercase')
    end
  end


  def text_with_link(notification)
    if notification.comment?
      notification.text
    else
      link_to notification.text, notification.resource_link
    end
  end

  # TODO: Delete all views for public_activity
  def render_notification(notification)
    # TODO: Add resource link
    [notification.resource_action, notification.text].join(' ')
  end
end

app/views/notifications/_notification_list.html.erb
<% notifications.each do |notification| %>
  <li class="<%= notification.read? ? '' : 'notification-unread' %>" data-notification-id="<%= notification.id %>">
    <span style="cursor: pointer; float: left;">
      <i class="fa fa-times" id="deleteNotificationBtn" aria-hidden="true"></i>
    </span>
    <span class="col-md-11" style="padding-right: 0;">
      <%= main_link(notification) %>
      <span class="text-capitalize">
        <b><%= notification.performer_name %></b>
        <%= notification.resource_action %>
        <%= text_with_link(notification) %>
      </span>
    </span>
  </li>
<% end %>

app/views/notifications/_notification_slider.html.erb
<div id="cd-shadow-layer"></div>
<div id="cd-cart">
  <h2>Notifications</h2>
  <div class="pull-right">
    <%= link_to 'Mark all read', mark_all_read_notifications_path, method: :patch, remote: true %>&nbsp;|&nbsp;
    <%= link_to 'Clear all', clear_all_notifications_path, method: :patch, remote: true %>
  </div>
  <div class="clearfix"></div>
  <ul class="cd-cart-items" id="notificationList">
    <!--populate notifications here-->
  </ul>
  <%= link_to 'Show More', notifications_path, :remote => true, :id => 'show_more_notifications' %>
  <p class="cd-go-to-cart"><a href="<%= notifications_path %>">Go to Notification Page</a></p>
</div>

app/views/notifications/_push_notice.html.erb
<!--TODO: Delete this file. No longer used -->
<% short_message[:commits].each do |commit|%>
    <div class="notification-message-container">
      <a href="#" class="notification-user" style="background-color: #AB5733"><%= short_message[:vcs_name] %></a>
      <a id="notice" class="success-edit"
         onclick=""><i class="fa fa-check-square"></i></a>
                      <span class="message-info"><b></b>
                        <%= short_message[:head]%>
                      </span>
      <div>
        <a href="<%= commit[:url]%>"> <%= commit[:id].last(7) %></a>
        <%= commit[:message]%>
      </div>
    </div>
<%end%>

app/views/notifications/clear_all.js.erb
//remove unread notification count
$('#badge.notification-badge').text('');
//remove all notifications
$('#notificationList').html('');

app/views/notifications/index.html.erb
<!--TODO: Fix view design -->
<ul class="cd-cart-items" id="notificationList">
  <%= render 'notification_list', notifications: @notifications %>
</ul>
<%= will_paginate @notifications %>

app/views/notifications/index.js.erb
$('#notificationList').append("<%= j (render 'notifications/notification_list', notifications: @notifications) %>");

var show_more_link = $("#show_more_notifications");

<% if @notifications.total_pages == @notifications.current_page %>
  show_more_link.hide();
<% else %>
  show_more_link.show();
  show_more_link.attr('href', "<%= notifications_path(page: @page+1) %>");
<% end %>

app/views/notifications/mark_all_read.js.erb
$('#badge.notification-badge').text('');
$('ul#notificationList li').removeClass('notification-unread');

app/views/notifications/old_index_grouped.html.erb
<!--TODO: Delete this file. No longer used-->
<!--TODO: Fix it later, for now removing this feature, after fixing uncomment below line and delete next line-->
<% #current_user.projects.each do |project| %>
<% [].each do |project| %>
    <div class="col-lg-12 col-md-12">
      <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default notification-panel">
          <div class="panel-heading unread-message" role="tab" id="headingOne">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#<%= project.id %>" aria-expanded="true" aria-controls="collapseOne">
              <h4 class="panel-title">
                <i class="fa fa-check-circle-o"></i> Project: <%= project.title %>
              </h4>
            </a>
          </div>
          <div id="<%= project.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
              <% project.payloads.each do |payload| %>
                  <% short_message = VCSFactory.new(payload).get_vcs.message %>
                  <%= render('push_notice', short_message: short_message) if payload.event == "push" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

<% notice_count = current_user.notifications.unread.count %>

<% @notifications.each_with_index do |(notifiable, notifications), index| %>
    <div class="col-lg-12 col-md-12">
      <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default notification-panel">
          <div class="panel-heading unread-message" role="tab" id="headingOne">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#<%= index %>" aria-expanded="true" aria-controls="collapseOne">
              <h4 class="panel-title">
                <i class="fa fa-check-circle-o"></i> <%= notifiable ? notifiable.title : 'Has been removed' %>
              </h4>
            </a>
          </div>
          <div id="<%= index %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
            <div class="panel-body">
              <% notifications.each do |notification| %>
                  <div class="notification-message-container">
                    <a href="#" class="notification-user" style="background-color: #AB5733">JB</a>
                    <a id="<%= notification.id %>notice" class="<%= notification.read? ? 'success-edit' : 'info' %>"
                       onclick="read_notice(<%= notification.id %>);"><i class="fa fa-check-square"></i></a>
                      <span class="message-info"><b><%= notification.performer_name %></b>
                        <%= notification.resource_action %>
                        <%= text_with_link(notification) %> -
                        <%= time_ago_in_words(notification.created_at) %></span>
                  </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>