config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :projects do
    collection do
      post :sort
    end

    member do
      get :settings
      get :contributors
    end

    resources :stories do
      collection do
        post :sort
        get :new_import
        post :import
      end

      member do
        post :close
      end

      patch :assign, :set_state, on: :member
      resources :comments
      resources :attachments, only: :attach do
        post :attach, on: :collection
      end
    end

    resources :discussions do
      resources :comments
    end

    resources :contributions, only: [:create, :destroy] do
      member do
        post 'resend_invitation'
        patch 'update_initials'
        patch 'update_role'
      end
    end

    resources :attachments do
      member do
        post 'download'
      end
      resources :comments
    end

    resources :events do
      get :get_events, on: :collection
    end

    resources :integrations, except: [:new], param: :secure_id do
      member do
        get :new_import
        post :start_import
        match :accept_payload, defaults: {formats: :json}, via: [:post, :head] # Trello sending HEAD request
      end

      constraints name: /#{Integration::AVAILABLE_INTEGRATIONS.join('|')}/ do
        get '/:name' => 'integrations#new', on: :collection, as: :list
      end
    end
  end

  resources :notification_settings, only: [:index, :update]

  resources :contributions, only: :join do
    get :join, on: :member
  end

  devise_for :users, :controllers => {omniauth_callbacks: 'users/omniauth_callbacks', :registrations => 'users/registrations'}

  devise_scope :user do
    match '/users/:id/finish_signup', :to => 'omniauth_callbacks#finish_signup', via: [:get, :patch], :as => :finish_signup
    match '/users/:id/associate_account', :to => 'omniauth_callbacks#associate_account', via: :patch, :as => :associate_account
  end

  resources :notifications do
    collection do
      patch 'mark_all_read'
      patch 'clear_all'
    end
  end
  root 'welcome#index'
  get 'notifications' => 'notifications#index'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger alert-dismissable" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <h4><%= pluralize(object.errors.count, "error") %> prohibited this <%= object.class.name %> from being saved:</h4>

    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |name, msg| %>
    <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
    <% end %>
<% end %>

app/views/shared/_navigation.html.erb
<!--TODO: Delete this partial, it is not being used -->

<nav class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "TeknukCamp", root_url, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse" >
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><%= link_to 'Notifications', notifications_path %></li>
      </ul>


      <ul class="nav navbar-nav" style="float: right">
        <% if current_user %>
        <% notice_count =  current_user.notifications.where(:status => 'unread').count %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-bell"></i><span id = "badge" class="badge custom_badge" <% if notice_count==0 %> <%= 'style=display:none'%><%end%> ><%= notice_count%></span><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <div class="container notification_drop_down">
              <div class="table-responsive">
                <table class="table table-hover" id="notification_table">
                  <span style="float: left;  border-top: none !important; "> Notifications</span>
                  <span style="float: right;  border-top: none !important; " > <%= link_to 'See all', notifications_path%></span>
                  <% current_user.notifications.last(5).reverse.each do |notification| %>
                      <tr id = "<%= notification.id%>" <% if notification.status =='unread' %> <%= 'class=info' %> <% end %> onclick="read_notice(<%= notification.id %>);">
                        <td>
                           <%= notification.activity.owner.name if notification.activity.owner %>
                           <%= render_activity notification.activity %>
                        </td>
                        <td><%= time_ago_in_words(notification.created_at) %> </td>
                      </tr>
                  <%end%>
                </table>
              </div>
            </div>
          </ul>
        </li>
        <%end%>
        <li>
          <% if current_user %>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Sign In', new_user_session_path %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_public_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-5 col-sm-6 footerleft ">
        <div class="logofooter"><%= ENV['APP_NAME'] %></div>
        <p>allows you to camp all your management tasks under one camp along with third party apps integration.</p>

        <p><i class="fa fa-map-pin"></i> 84 G, DHA Masjid Chowk Phase 1 Lahore</p>

        <p><i class="fa fa-phone"></i> Phone (Pakistan) : 042-31234567</p>

        <p><i class="fa fa-envelope"></i> E-mail : info@camone.com</p>

        <div class="social">
          <a class="fa fa-facebook" title="" target="_blank" href="#"></a>
          <a class="fa fa-twitter" title="" target="_blank" href="#"></a>
          <a class="fa fa-google" title="" target="_blank" href="#"></a>
          <a class="fa fa-linkedin" title="" target="_blank" href="#"></a>
          <a class="fa fa-dribbble" title="" target="_blank" href="#"></a>
        </div>
      </div>
      <div class="col-md-2 col-sm-6">
        <h6 class="footer-heading">GENERAL LINKS</h6>
        <ul class="footer-ul">
          <li><a href="#"><i class="fa fa-angle-double-right" aria-hidden="true"></i> Privacy Policy</a></li>
          <li><a href="#"><i class="fa fa-angle-double-right" aria-hidden="true"></i> Terms & Conditions</a></li>
          <li><a href="#"><i class="fa fa-angle-double-right" aria-hidden="true"></i> Client Gateway</a></li>
          <li><a href="#"><i class="fa fa-angle-double-right" aria-hidden="true"></i> Ranking</a></li>
          <li><a href="#"><i class="fa fa-angle-double-right" aria-hidden="true"></i> Case Studies</a></li>
          <li><a href="#"><i class="fa fa-angle-double-right" aria-hidden="true"></i> FAQ </a></li>
        </ul>
      </div>
      <div class="col-md-5 col-sm-6">
        <h6 class="footer-heading">LATEST POST</h6>

        <div class="post">
          <blockquote>
            <p>facebook crack the movie advertisment code:what it means for you <br>
              <footer>August 3,2015</footer>
            </p>
          </blockquote>
          <blockquote>
            <p>facebook crack the movie advertisment code:what it means for you <br>
              <footer>August 3,2015</footer>
            </p>
          </blockquote>
          <blockquote>
            <p>facebook crack the movie advertisment code:what it means for you <br>
              <footer>August 3,2015</footer>
            </p>
          </blockquote>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_public_nav.html.erb
<nav class="navbar navbar-landing top-nav-collapse mg-b50" role="navigation">
  <div class="container">
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
        <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">
        <i class="fa fa-play-circle"></i> <span class="light text-uppercase"><%= ENV['APP_NAME'] %></span>
      </a>
    </div>
    <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
      <ul class="nav navbar-nav">
        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
        <li class="hidden"><a></a></li>
        <!--<li><a href="<%= new_user_session_path %>"><i class="fa fa-sign-in"></i> Login</a></li>-->
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_public_navbar.html.erb
<nav class="navbar navbar-landing navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
        <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">
        <i class="fa fa-play-circle"></i> <span class="light text-uppercase"><%= ENV['APP_NAME'] %></span>
      </a>
    </div>
    <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
      <ul class="nav navbar-nav">
        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
        <li class="hidden"><a></a></li>

        <% if @available_sections[:features] %>
          <li class="page-scroll"><a href="#features">Features</a></li>
        <% end %>

        <% if @available_sections[:pricing] %>
          <li class="page-scroll"><a href="#pricing">Pricing</a></li>
        <% end %>

        <% if @available_sections[:reviews] %>
          <li class="page-scroll"><a href="#reviews">Reviews</a></li>
        <% end %>

        <% if @available_sections[:contact_us] %>
          <li class="page-scroll"><a href="#contact">Contact Us</a></li>
        <% end %>

        <li class="dropdown">
          <a class="dropdown-toggle" href="#" data-toggle="dropdown"><i class="fa fa-sign-in"></i> Login</a>

          <div class="dropdown-menu login-dropdown">
            <div class="row">
              <div class="col-md-12">
                <span>Login</span>
                <!--TODO: temporary hide social icon-->
                <div class="social mg-t10 mg-b10 hidden">
                  <a class="fa fa-facebook" title="" target="_blank" href="#"></a>
                  <a class="fa fa-twitter" title="" target="_blank" href="#"></a>
                  <a class="fa fa-google" title="" target="_blank" href="#"></a>
                  <a class="fa fa-linkedin" title="" target="_blank" href="#"></a>
                  <a class="fa fa-dribbble" title="" target="_blank" href="#"></a>
                </div>
                <div class="text-center mg-b10 hidden">or</div>
                <%= form_for(:user, :url => session_path(:user), html: {class: 'mg-t10'}) do |f| %>
                  <div class="form-group">
                    <%= f.text_field :login, class: 'form-control', placeholder: 'Username or Email', id: 'login_user_email' %>
                  </div>
                  <div class="form-group">
                    <div class="form-group">
                      <%= f.password_field :password, class: 'form-control', placeholder: 'Password', id: 'login_user_password' %>
                    </div>

                    <div class="help-block text-right">
                      <%= link_to 'Forgot your password?', new_password_path(:user) %>
                    </div>
                  </div>
                  <div class="form-group">
                    <%= f.submit 'Login', class: 'btn btn-primary btn-block' %>
                  </div>
                  <div class="checkbox">
                    <label>
                      <%= f.check_box :remember_me %>
                      <%= f.label :remember_me, 'keep me logged-in', style: 'padding-left: 5px;' %>
                    </label>
                  </div>
                <% end %>
              </div>
              <div class="bottom text-center">
                New here ? <a href="<%= new_user_registration_path %>"><b>Join Us</b></a>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_settings.html.erb
<% content_for(:tab_nav) do %>
    <%= render 'shared/tab_nav', project: project, active: 'settings' %>
<% end %>

<div class='settings'>
  <div class='col-lg-2 col-md-2 col-sm-2 col-xs-3 menu'>
    <div class='list-group'>
      <% if project.blank? %>
          <a href='<%= edit_user_registration_path %>' class='list-group-item <%= 'active' if active == 'account' %>'>
            Account Settings
          </a>
          <a href='<%= notification_settings_path %>' class='list-group-item <%= 'active' if active == 'notification' %>'>
            Notification Settings
          </a>
      <% else %>
          <a href='<%= settings_project_path(project) %>' class='list-group-item <%= 'active' if active == 'settings' %>'>
            Project Settings
          </a>
          <a href='<%= contributors_project_path(project) %>' class='list-group-item pd-l30 <%= 'active' if active == 'contributors' %>'>
            Contributors Settings
          </a>
          <% if can? :create, Integration.new(project: project) %>
              <a href='<%= project_integrations_path(project) %>' class='list-group-item pd-l30 <%= 'active' if active == 'integrations' %>'>
                Integrations Settings
              </a>
          <% end %>
      <% end %>
    </div>
  </div>
  <div class='col-lg-9 col-md-9 col-sm-9 col-xs-9 body'>
    <h2>
      <%= title %>
    </h2>
    <hr>
    <%= yield :settings_body %>
  </div>
</div>

app/views/shared/_settings_tab.html.erb
<div class='col-lg-2 col-md-2 col-sm-2 col-xs-3 custom-tab-menu'>
  <div class='list-group'>
    <a href='<%= settings_project_path(project) %>' class='list-group-item <%= "#{class_name}" if active == 'settings' %>'>
      Project Settings
    </a>
    <a href='<%= contributors_project_path(project) %>' class='list-group-item pd-l30 <%= "#{class_name}" if active == 'contributors' %>'>
      Contributors Settings
    </a>
    <a href='<%= notification_settings_path %>' class='list-group-item pd-l30 <%= "#{class_name}" if active == 'notification' %>'>
      Notification Settings
    </a>
    <% if can? :create, Integration.new(project: project) %>
        <a href='<%= project_integrations_path(project) %>' class='list-group-item pd-l30 <%= "#{class_name}" if active == 'integrations' %>'>
          Integrations Settings
        </a>
    <% end %>
  </div>
</div>

app/views/shared/_tab_nav.html.erb
<div class="custom-container">
  <ul class="nav nav-tabs" role="tablist">
    <% if project.present? %>
        <li role="presentation" class=<%= 'active' if active == 'todos' %>>
          <a href="<%= project_stories_path(project) %>">
            <i class="fa fa-check-circle-o mg-r10"></i>
            Stories
          </a>
        </li>
        <li role="presentation" class=<%= 'active' if active == 'discussion' %>>
          <a href="<%= project_discussions_path(project) %>">
            <i class="fa fa-comments-o mg-r10"></i>
            Discussions
          </a>
        </li>
        <li role="presentation" class=<%= 'active' if active == 'files' %>>
          <a href="<%= project_attachments_path(project) %>">
            <i class="fa fa-folder-open-o mg-r10"></i>
            Files
          </a>
        </li>
        <li role="presentation" class="pull-right <%= 'active' if active == 'settings' %>">
          <a href="<%= settings_project_path(project) %>">
            <i class="fa fa-cog mg-r10"></i>
            Project Settings</a>
        </li>
        <li class="pull-right <%= active == 'todos' ? 'show' : 'hidden' %> ">
          <%= yield :search_stories if content_for?(:search_stories) %>
        </li>

        <li class="pull-right custom-tooltip <%= active == 'todos' ? 'show' : 'hidden' %> ">
          <%= yield :show_hide_completed if content_for?(:show_hide_completed) %>
        </li>
    <% else %>
        <li role="presentation" class="pull-right <%= 'active' if active == 'settings' %>">
          <a href="#">
            <i class="fa fa-cog mg-r10"></i>
            Settings
          </a>
        </li>
    <% end %>
  </ul>
</div>

app/views/shared/_top_navigation.html.erb
<nav class="navbar navbar-default dasboard-navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="<%= projects_path %>" style="font-size: 14px;"><%= ENV['APP_NAME'] %></a></li>
        <li>
          <% if @project && @project.persisted? %>
              <%= link_to @project.title, project_stories_path(@project), class: 'navbar-brand caret-before' %>
          <% else %>
              <span class="navbar-brand caret-before">Select Project</span>
          <% end %>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle caret-after" data-toggle="dropdown" style="padding-top: 12px; padding-bottom: 12px;">
            <i class="fa fa-angle-double-down fa-2x" aria-hidden="true"></i>
          </a>
          <ul class="dropdown-menu dropdown-menu-right">
            <% current_user && current_user.projects.each do |project| %>
                <li><a href="<%= project_stories_path(project) %>"><%= project.title %></a></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if current_user %>
          <ul class="nav navbar-nav navbar-right">
            <li class="badge-list">
              <a class="dashboard-nav" id="cd-cart-trigger" title="Notification">
                <% notice_count = current_user.notifications.unread.count %>
                <i class="fa fa-bell-o"></i>
            <span id="badge" class="badge notification-badge"
                  <% if notice_count==0 %> <%= 'style=display:none' %><% end %> >
              <%= notice_count %>
            </span>
              </a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %>
                <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="<%= edit_user_registration_path %>">My Account</a></li>
                <li><a href="<%= notification_settings_path %>">Notification Settings</a></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
      <% end %>
    </div>
  </div>
</nav>