config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :projects do
    collection do
      post :sort
    end

    member do
      get :settings
      get :contributors
    end

    resources :stories do
      collection do
        post :sort
        get :new_import
        post :import
      end

      member do
        post :close
      end

      patch :assign, :set_state, on: :member
      resources :comments
      resources :attachments, only: :attach do
        post :attach, on: :collection
      end
    end

    resources :discussions do
      resources :comments
    end

    resources :contributions, only: [:create, :destroy] do
      member do
        post 'resend_invitation'
        patch 'update_initials'
        patch 'update_role'
      end
    end

    resources :attachments do
      member do
        post 'download'
      end
      resources :comments
    end

    resources :events do
      get :get_events, on: :collection
    end

    resources :integrations, except: [:new], param: :secure_id do
      member do
        get :new_import
        post :start_import
        match :accept_payload, defaults: {formats: :json}, via: [:post, :head] # Trello sending HEAD request
      end

      constraints name: /#{Integration::AVAILABLE_INTEGRATIONS.join('|')}/ do
        get '/:name' => 'integrations#new', on: :collection, as: :list
      end
    end
  end

  resources :notification_settings, only: [:index, :update]

  resources :contributions, only: :join do
    get :join, on: :member
  end

  devise_for :users, :controllers => {omniauth_callbacks: 'users/omniauth_callbacks', :registrations => 'users/registrations'}

  devise_scope :user do
    match '/users/:id/finish_signup', :to => 'omniauth_callbacks#finish_signup', via: [:get, :patch], :as => :finish_signup
    match '/users/:id/associate_account', :to => 'omniauth_callbacks#associate_account', via: :patch, :as => :associate_account
  end

  resources :notifications do
    collection do
      patch 'mark_all_read'
      patch 'clear_all'
    end
  end
  root 'welcome#index'
  get 'notifications' => 'notifications#index'

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                :integer          not null, primary key
#  title             :string
#  description       :text
#  owner_id          :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  slug              :string
#  current_ticket_id :integer          default(1)
#

class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :title_initials, use: [:slugged, :finders]

  acts_as_tagger
  # Now we can remove owner from project, as we have added owner role in Contribution, see #add_owner_to_contributors
  belongs_to :owner, class_name: 'User'

  # deleting a project will delete its stories, discussions and attachments (including comments, attachments)
  # which can break notifications
  # TODO: Fix notifications making them flat
  # TODO: Update deleting mechanism (Ask for project name)
  has_many :contributions, dependent: :destroy
  has_many :members, through: :contributions, :source => :user

  has_many :stories, dependent: :destroy
  has_many :discussions, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :attachments, as: :attachable, class_name: 'ProjectAttachment', dependent: :destroy

  has_many :integrations, dependent: :destroy
  has_many :payloads, through: :integrations

  validates :title, presence: true
  validates :owner, presence: true

  after_create :add_owner_to_contributors

  delegate :url_helpers, to: 'Rails.application.routes'
  alias :h :url_helpers

  def joined_members
    members.merge(Contribution.joined)
  end

  # TODO: Refactor and simplify
  # UA[2016/12/06] - SHOULDN'T WE USE TRANSACTIONS ???
  def create_attachments(attachments, uploaded_by)
    return if attachments.blank?

    attachments.each do |attachment|
      self.attachments.create(document: attachment, title: attachment.original_filename, performer: uploaded_by, project_id: self.id)
    end
  end

  def json_events_for_calender
    all_events = []

    stories.each do |story|
      all_events << {
        :id      => story.id,
        :title   => "#{ story.title }",
        :start   => "#{ story.due_at }",
        :editUrl => "#{ h.edit_project_story_path story.project, story }"
      }
    end

    events.each do |event|
      all_events << {
        :id          => event.id,
        :title       => "#{ event.title }",
        :description => "#{ event.description }",
        :start       => "#{ event.due_at }",
        :editUrl     => "#{ h.edit_project_event_path event.project, event }"
      }
    end

    return all_events.to_json
  end

  def normalize_friendly_id(initials)
    postfix = initials.length.equal?(1) ? 1 : ''
    while Project.exists?(slug: "#{initials}#{postfix}") do
      postfix = (postfix || 0) + 1
    end
    "#{initials}#{postfix}"
  end

  private

  def add_owner_to_contributors
    position = self.owner.projects.maximum(:position) ? self.owner.projects.maximum(:position) + 1 : 1
    self.contributions.create(user: self.owner, status: 'joined', role: Contribution::ROLES[:owner], position: position)
  end

  def title_initials
    (self.title || 'p r o').split.map(&:first).join.downcase
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource
  before_action :set_project, only: [:show, :edit, :update, :destroy, :settings, :contributors, :integrations]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.contributions.order('position').map(&:project)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    redirect_to project_stories_path(@project)
    # @contribution = Contribution.new
    # @contributions = @project.contributions
    #
    # @integration = Integration.new
    # @integrations = @project.integrations.all
  end

  def settings
  end

  def contributors
    @contribution = Contribution.new(project: @project)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params.merge(owner: current_user))

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to settings_project_path(@project), notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy

    respond_to do |format|
      format.html do
        if @project.title == params[:confirm_project]
          @project.destroy
          redirect_to projects_url, notice: 'Project was successfully destroyed.'
        else
          redirect_back(fallback_location: project_path(@project), notice: 'Project verification failed.')
        end
      end

      format.json { head :no_content }
    end
  end

  def sort
    params[:project].each_with_index do |id, index|
      Contribution.find_by(project_id: id, user: current_user).update_attributes(position: index+1)
    end
    render :nothing => true
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:title, :description)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_delete_project_modal.html.erb
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Delete Project Confirmation </h4>
      </div>
      <div class="modal-body">
        <p>Are you ABSOLUTELY sure?<br>
          Unexpected bad things will happen if you don't read this!
        </p>
        <p>This action CANNOT be undone. This will permanently delete the <%= project.title %> project, stories, discussions, and comments, and remove all member associations.</p>

        <p>Please type in the name of the project to confirm.</p>

        <%= form_tag(project_path(project), method: :delete) do %>
          <div class="form-group">
            <%= text_field_tag :confirm_project, nil, class: 'form-control' %>
          </div>
          <%= submit_tag 'Delete', class: "btn btn-danger" %>
        <% end %>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/projects/_form.html.erb
<%= form_for(@project, html: {role: "form", class: "form-horizontal"}) do |f| %>
    <div class="container-fluid">
      <%= render 'shared/error_messages', object: @project %>

      <div class="form-group">
        <%= f.label :title, class: "col-md-2 control-label" %>
        <div class="col-md-10" placeholder="Software X, Yosemite">
          <%= f.text_field :title, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :description, class: "col-md-2 control-label" %>
        <div class="col-md-10" placeholder="Project Description">
          <%= f.text_area :description, class: "form-control" %>
        </div>
      </div>
      <div class="form-group text-center">
        <%= f.submit class: "btn btn-info" %>
      </div>
    </div>
<% end %>

app/views/projects/contributors.html.erb
<% content_for(:settings_body) do %>
    <% if can? :create, @contribution %>
        <p>
          Invite a new member to
          <strong>
            <%= @project.title %>
          </strong>
        </p>
        <div class='mg-b30'>
          <%= form_for [@project, @contribution], html: {class: 'form-inline'} do |f| %>
              <div class="form-group mg-r10">
                <%= f.label :email %>
                <%= f.text_field :email, class: 'form-control' %>
              </div>
              <div class="form-group mg-r10">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
              </div>
              <div class="form-group mg-r10">
                <%= f.label :role %>
                <%= f.select :role, options_for_select(Contribution::ROLES.values - ['Owner'], selected: @contribution.role), {}, class: 'form-control' %>
              </div>
              <%= f.submit 'Invite', class: 'btn btn-success' %>
          <% end %>
        </div>
    <% end %>

    <p>
      Existing Members for
      <strong>
        <%= @project.title %>
      </strong>
    </p>
    <% if @project.contributions.present? %>
        <%= render 'contributions/list', contributions: @project.contributions %>
    <% else %>
        <p class="text-center">No Contributions Found.</p>
    <% end %>
<% end %>

<%= render 'shared/settings', project: @project, active: 'contributors', title: 'Project Members' %>

app/views/projects/edit.html.erb
<% content_for(:settings_body) do %>
    <%= form_for(@project, html: {role: 'form', class: 'form-horizontal'}) do |f| %>
        <%= render 'shared/error_messages', object: @project %>
        <table class="table borderless">
          <tr>
            <th class="text-right col-md-2"><%= f.label :title, 'Title:', class: 'control-label' %></th>
            <td class="col-md-10"><%= f.text_field :title, class: 'form-control' %></td>
          </tr>
          <tr>
            <th class="text-right"><%= f.label :description, 'Description:', class: 'control-label' %></th>
            <td><%= f.text_area :description, class: 'form-control' %></td>
          </tr>
          <tr>
            <td>&nbsp;</td>
            <td>
              <%= f.button class: 'btn btn-primary' do %>
                  <span class='glyphicon glyphicon-save'></span>
                  Update
              <% end %>
              <%= link_to settings_project_path(@project), class: 'btn btn-default' do %>
                  <span class='glyphicon glyphicon-arrow-left'></span>
                  Back
              <% end %>
            </td>
          </tr>
        </table>
    <% end %>
<% end %>

<%= render 'shared/settings', project: @project, active: 'settings', title: 'Project Settings' %>

app/views/projects/index.html.erb
<div class="custom-content-container">
<div class="row">
  <div class="col-md-12 col-sm-12 nopadding-left">
    <%= link_to new_project_path, class: 'create-project' do %>
      Create New Project
      <span><i class="fa fa-plus-circle"></i></span>
    <% end %>
    <div class="col-md-10 col-sm-8 nopadding-left">
      <section class="bg-white ">
        <div class="dragable" id="project" data-update-url="<%= sort_projects_url %>">
          <% @projects.each do |project| %>
              <div class="project anchor-container" id="project_<%= project.id %>" data-href="<%= project_stories_path(project) %>">
                <h3 class="project-title"><%= project.title %></h3>

                <div class="color_corner" style="border-right-color: #DC4138;">
                  <div class="triangle"></div>
                </div>
                <div class="cog_container">
                  <span class="cog-setting"><i class="fa fa-cog"></i></span>
                </div>
                <p class="project-description mg-b10"><%= project.description %></p>

                <div class="project-apps mg-b50">
                  <a href="<%= project_stories_path(project) %>" class="project-icon" data-toggle="tooltip" data-placement="bottom" title="Stories"><i class="fa fa-check-circle-o"></i></a>
                  <a href="<%= project_discussions_path(project) %>" class="project-icon" data-toggle="tooltip" data-placement="bottom" title="Discussions"><i class="fa fa-comments-o"></i></a>
                  <a href="<%= project_attachments_path(project) %>" class="project-icon" data-toggle="tooltip" data-placement="bottom" title="Files"><i class="fa fa-folder-open-o"></i></a>
                  <a href="<%= project_events_path(project) %>" class="project-icon" data-toggle="tooltip" data-placement="bottom" title="Calendar"><i class="fa fa-calendar"></i></a>
                </div>
                <div class="project-user">
                  <a href="#" style="background-color: #AB5733">JB</a>
                  <a href="#" style="background-color: #DC4138">GS</a>
                  <a href="#" style="background-color: #329350">TJ</a>
                  <a href="#" style="background-color: #E8BB46">UA</a>
                </div>
              </div>
          <% end %>
        </div>
      </section>
    </div>
  </div>
</div>
</div>

app/views/projects/new.html.erb
<div class="col-md-6 col-md-offset-3 text-center">
  <%= image_tag('logo.png') %>

  <h2>Create a project</h2>
  <div class="invite-form">
    <%= render 'form' %>
  </div>
</div>

app/views/projects/settings.html.erb
<% content_for(:settings_body) do %>
    <table class="table borderless">
      <tr>
        <th class="text-right col-md-2">Title:</th>
        <td class="col-md-10"><%= @project.title %></td>
      </tr>
      <tr>
        <th class="text-right">Owner:</th>
        <td><%= @project.owner.name %></td>
      </tr>
      <tr>
        <th class="text-right">Description:</th>
        <td><%= @project.description %></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td>
          <% if can? :edit, @project %>
              <%= link_to edit_project_path(@project), class: 'btn btn-primary' do %>
                  <span class='glyphicon glyphicon-pencil'></span>
                  Edit
              <% end %>
          <% end %>

          <% if can? :destroy, @project %>
              <button type='button' class='btn btn-danger' data-toggle='modal' data-target='#myModal'>
                <span class='glyphicon glyphicon-trash'></span> Delete
              </button>
              <%= render 'projects/delete_project_modal', project: @project %>
          <% end %>
        </td>
      </tr>
    </table>
<% end %>

<%= render 'shared/settings', project: @project, active: 'settings', title: 'Project Settings' %>

app/views/projects/show.html.erb
<% content_for(:tab_nav) do %>
    <%= render 'shared/tab_nav', project: @project, active: 'settings' %>
<% end %>
<div class="custom-tab-container">
  <div class="col-lg-2 col-md-2 col-sm-2 col-xs-3 custom-tab-menu">
    <div class="list-group">
      <a href="#" class="list-group-item active">
        Project Settings
      </a>
      <a href="#" class="list-group-item">
        Users Settings
      </a>
      <a href="#" class="list-group-item">
        Integrations Settings
      </a>
    </div>
  </div>
  <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9 custom-tab">
    <!-- user section -->
    <div class="custom-tab-content active">
      <div class="tab-content-header">
        <h3 class="heading-3">Project Settings</h3>

        <div class="pull-right">
          <%= link_to edit_project_path(@project), class: 'btn btn-primary' do %>
              <span class="glyphicon glyphicon-pencil"></span>
              Edit
          <% end %>

          <% if can? :destroy, @project %>
              <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
                <span class="glyphicon glyphicon-trash"></span> Delete
              </button>
              <%= render 'projects/delete_project_modal', project: @project %>
          <% end %>
        </div>
      </div>
      <hr>
      <div class="col-md-2">
        <h5>Title:</h5>

        <p><%= @project.title %></p>
      </div>
      <div class="col-md-2">
        <h5>Owner:</h5>

        <p><%= @project.owner.name %></p>
      </div>
      <div class="col-md-8">
        <h5>Description:</h5>

        <p><%= @project.description %></p>
      </div>
    </div>
    <div class="custom-tab-content">
      <div class="tab-content-header">
        <h3 class="heading-3">Users Settings</h3>
      </div>
      <hr>
      <div class="col-md-12">
        <%= render 'contributions/list' %>
      </div>
      <div class="col-md-6 mg-b20">
        <%= render 'contributions/form' %>
      </div>
    </div>
    <div class="custom-tab-content">
      <div class="tab-content-header">
        <h3 class="heading-3">Integrations</h3>
      </div>
      <hr>
      <div class="col-md-12">
        <%= render 'integrations/list' %>
      </div>
      <div>
        <%= render 'integrations/available_integrations' %>
      </div>
    </div>
  </div>
</div>