config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  resources :projects do
    collection do
      post :sort
    end

    member do
      get :settings
      get :contributors
    end

    resources :stories do
      collection do
        post :sort
        get :new_import
        post :import
      end

      member do
        post :close
      end

      patch :assign, :set_state, on: :member
      resources :comments
      resources :attachments, only: :attach do
        post :attach, on: :collection
      end
    end

    resources :discussions do
      resources :comments
    end

    resources :contributions, only: [:create, :destroy] do
      member do
        post 'resend_invitation'
        patch 'update_initials'
        patch 'update_role'
      end
    end

    resources :attachments do
      member do
        post 'download'
      end
      resources :comments
    end

    resources :events do
      get :get_events, on: :collection
    end

    resources :integrations, except: [:new], param: :secure_id do
      member do
        get :new_import
        post :start_import
        match :accept_payload, defaults: {formats: :json}, via: [:post, :head] # Trello sending HEAD request
      end

      constraints name: /#{Integration::AVAILABLE_INTEGRATIONS.join('|')}/ do
        get '/:name' => 'integrations#new', on: :collection, as: :list
      end
    end
  end

  resources :notification_settings, only: [:index, :update]

  resources :contributions, only: :join do
    get :join, on: :member
  end

  devise_for :users, :controllers => {omniauth_callbacks: 'users/omniauth_callbacks', :registrations => 'users/registrations'}

  devise_scope :user do
    match '/users/:id/finish_signup', :to => 'omniauth_callbacks#finish_signup', via: [:get, :patch], :as => :finish_signup
    match '/users/:id/associate_account', :to => 'omniauth_callbacks#associate_account', via: :patch, :as => :associate_account
  end

  resources :notifications do
    collection do
      patch 'mark_all_read'
      patch 'clear_all'
    end
  end
  root 'welcome#index'
  get 'notifications' => 'notifications#index'

end

app/models/contribution.rb
# == Schema Information
#
# Table name: contributions
#
#  id         :integer          not null, primary key
#  project_id :integer
#  user_id    :integer
#  role       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  token      :string
#  status     :string           default("pending")
#  inviter_id :integer
#  position   :integer
#  initials   :string
#

class Contribution < ApplicationRecord
  belongs_to :project
  belongs_to :user
  belongs_to :inviter, class_name: 'User'

  attr_accessor :email, :name, :user_just_created

  before_validation :invite_and_set_user_and_set_initials
  before_create :generate_token
  before_create :set_position

  validates :initials,
            uniqueness: {scope: [:project_id], case_sensitive: false},
            length: 2..4

  scope :joined, -> {where(status: 'joined')}

  ROLES = {
      guest: 'Guest',
      member: 'Member',
      manager: 'Manager',
      owner: 'Owner',
  }

  STATUSES = %w(pending joined)

  validates :user, presence: {message: 'not created. Please make sure that you have entered a valid email.'},
            uniqueness: {scope: :project, message: 'Already invited on this project.'}
  validates :role, inclusion: {in: ROLES.values}
  validates :status, inclusion: {in: STATUSES}

  def send_invitation_email
    if user.invitation_accepted? # UA[2019/02/26] user must exist for send_invitation_email
      UserMailer.contribution_mail(self).deliver
    else
      user.invite!(inviter, invite_by_devise_options(user.name, user.email))
    end
  end

  # UA[2019/03/05] source of issues for #create, we assign email as an attr_accessor but get nil as result
  # def email
  #   user.try(:email)
  # end

  private

  def invite_and_set_user_and_set_initials
    user = self.user || User.find_by(email: email)
    self.user_just_created = true unless user
    # TODO: Refactor, Do not send invite if contribution is not valid ... https://stackoverflow.com/questions/1242617/rails-partial-table-validations
    user ||= User.invite!({email: email, name: name}, inviter, invite_by_devise_options(name, email))
    self.user = user if user.persisted?
    set_initials
  end

  def invite_by_devise_options(name, email)
    # TODO: RECHECK and Make the use of I18n and locale files proper
    {
        name_or_email: name || email,
        project_title: project.title,
        inviter_name: inviter.name,
        subject: I18n.t('devise.mailer.invitation_instructions.subject',
                        inviter_name: inviter.name, project_title: project.title)
    }
  end

  def set_initials
    return if self.initials.present?
    source = self.user.name || self.user.email
    name_initials = source.split(' ').map {|x| x[0]}.join()[0..1].upcase
    postfix = name_initials.length.equal?(1) ? 1 : ''
    while self.project.contributions.exists?(initials: "#{name_initials}#{postfix}") do
      postfix = (postfix || 0) + 1
    end
    self.initials = "#{name_initials}#{postfix}".upcase
  end

  def generate_token
    self.token = "#{project.friendly_id}-#{SecureRandom.hex(15).encode('UTF-8')}"
  end

  def set_position
    self.position = self.user.projects.maximum(:position) ? self.user.projects.maximum(:position) + 1 : 1
  end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  # This hook must come before authorization
  before_action :set_contribution_by_token, only: [:join]

  load_and_authorize_resource :project
  load_and_authorize_resource :contribution, through: :project

  def create
    contribution = @project.contributions.build(contribution_params.merge(inviter: current_user))
    if contribution.save
      # send invitation email if user exist in system (prevent duplicate email if already sent by devise invitable)
      contribution.send_invitation_email unless contribution.user_just_created
      flash[:alert] = 'Invitations sent.'
    else
      flash[:alert] = contribution.errors.full_messages.join
    end

    redirect_back(fallback_location: project_path(@project))
  end

  def resend_invitation
    @contribution.send_invitation_email
    flash[:alert] = 'Invitation email sent successfully.'
    redirect_back(fallback_location: project_path(@project))
  end

  def join
    if @contribution.update_attributes(status: 'joined')
      flash[:alert] = 'You have successfully joined this project.'
    else
      flash[:alert] = 'Something went wrong. We are unable to change your status.'
    end

    redirect_to project_stories_path(@contribution.project)
  end

  # UA[2019/02/25] TODO: Remove extra files after testing on production
  # def index
  # end
  #
  # def new
  #   @contribution = Contribution.new
  #   @contributions = @project.contributions
  # end
  #
  # def edit
  # end
  #
  # def update
  #   @contribution.assign_attributes(contribution_params)
  #
  #   # if cannot create contribution with above given values
  #   if cannot? :update, @contribution
  #     flash[:alert] = 'You can not assign these values.'
  #   elsif @contribution.save
  #     flash[:alert] = 'Updated successfully.'
  #   else
  #     flash[:alert] = @contribution.errors.full_messages.join
  #   end
  #
  #   redirect_back(fallback_location: contributors_project_path(@project))
  # end

  def update_initials
    if @contribution.update(initials: params[:contribution][:initials])
      respond_to do |format|
        format.html {redirect_back fallback_location: contributors_project_path(@project), notice: 'Initials successfully updated.'}
        format.json {render @contribution.as_json}
      end
    else
      respond_to do |format|
        format.html {redirect_back fallback_location: contributors_project_path(@project), alert: 'Initials could not be updated.'}
        format.json {render json: @contribution.errors.full_messages, status: :unprocessable_entity}
      end
    end
  end

  def update_role
    if @contribution.update(role: params[:contribution][:role])
      respond_to do |format|
        format.html {redirect_back fallback_location: contributors_project_path(@project), notice: 'Role successfully updated.'}
        format.json {render @contribution.as_json}
      end
    else
      respond_to do |format|
        format.html {redirect_back fallback_location: contributors_project_path(@project), alert: @contribution.errors.full_messages.join(' ')}
        format.json {render json: @contribution.errors.full_messages, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @contribution.destroy
    redirect_back fallback_location: contributors_project_path(@project), notice: 'Removed from contributors.'
  end

  private

  # def set_contribution
  #   @contribution = @project.contributions.where(user: current_user).first
  # end

  def set_contribution_by_token
    @contribution = Contribution.where(token: params[:id]).first
  end

  def contribution_params
    params.require(:contribution).permit(:email, :role, :name, :initials)
  end
end

app/helpers/contributions_helper.rb
module ContributionsHelper
  # def joined_status(contribution)
  #   # contribution.user.invitation_accepted? ? 'Joined' : 'Awaiting'
  #   contribution.status
  # end
end

app/views/contributions/_form.html.erb
<%= form_for [@project, @contribution], html: {role: "form", class: 'form-inline'} do |f| %>
    <% if @contribution.new_record? %>
        <div class="form-group mg-r10">
          <%= f.label :email %>
          <%= f.text_field :email, class: "form-control" %>
        </div>
        <div class="form-group mg-r10">
          <%= f.label :name  %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
    <% else %>
        <div class="form-group mg-r10">
          <label>Email: </label>
          <%= @contribution.user.email %>
        </div>
        <div class="form-group mg-r10">
          <label>Initials: </label>
          <%= @contribution.initials %>
        </div>
    <% end %>
    <div class="form-group mg-r10">
      <%= f.label :role, 'Role:' %>
      <%= f.select :role, options_for_select(Contribution::ROLES.values - ['Owner'], selected: @contribution.role), {}, class: "form-control" %>
    </div>
    <%= f.submit @contribution.new_record? ? "Invite" : "Update", class: "btn btn-success" %>
<% end %>

app/views/contributions/_list.html.erb
<table class="table table-striped table-bordered table-hover">
  <tr>
    <th class="col-md-2">Name</th>
    <th class="col-md-2">Email</th>
    <th class="col-md-2">Initials</th>
    <th class="col-md-2">Role</th>
    <!--<th class="col-md-1">Status</th>-->
    <th class="col-md-3">Actions</th>
  </tr>
  <% contributions.each do |contribution| %>
      <tr>
        <td>
          <%= contribution.user.name %>
          <br>
          <%= content_tag(:label, "It's You", class: 'label label-info') if current_user.eql?(contribution.user) %>
        </td>
        <td><%= contribution.user.email %></td>
        <td class="initials"><%= contribution.initials %></td>
        <td style="display: none">
          <% if current_user.eql?(contribution.user) %>
              <%= form_for [:update_initials, contribution.project, contribution] do |f| %>
                  <%= f.text_field :initials, class: 'form-control', style: 'margin-bottom: 5px;' %>
                  <%= f.submit 'Update', class: 'btn btn-success' %>
              <% end %>
          <% end %>
        </td>
        <td class="role"><%= contribution.role %></td>
        <td style="display: none">
          <% if can?(:update_role, contribution) %>
              <%= form_for [:update_role, contribution.project, contribution] do |f| %>
                  <%= f.select :role, options_for_select(Contribution::ROLES.values - ['Owner'], selected: contribution.role),
                               {}, class: 'form-control', style: 'margin-bottom: 5px;' %>
                  <%= f.submit 'Update', class: 'btn btn-success' %>
              <% end %>
          <% end %>
        </td>
        <!--<td><%= contribution.status if can?(:resend_invitation, contribution) %></td>-->
        <td>
          <%= link_to_if_can(:update_initials, contribution, 'Edit Initials', '#', class: 'btn btn-default initials') %>

          <% if !contribution.user.invitation_accepted? && can?(:resend_invitation, contribution) %>
              <%= button_to 'Resend Invitation', resend_invitation_project_contribution_path(contribution.project, contribution),
                            method: :post, class: 'btn btn-default', form: {style: 'display: inline-block;'} %>
          <% end %>

          <%= link_to_if_can(:update_role, contribution, 'Edit Role', '#', class: 'btn btn-default role') %>

          <%= button_to_if_can(:destroy, contribution, 'Remove', project_contribution_path(contribution.project, contribution),
                               method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-default',
                               form: {style: 'display: inline-block;'}) %>
        </td>
      </tr>
  <% end %>
</table>

app/views/contributions/edit.html.erb
<% content_for(:tab_nav) do %>
    <%= render 'shared/tab_nav', project: @project, active: 'settings' %>
<% end %>
<div class='custom-tab-container'>
  <%= render 'shared/settings_tab', project: @project, class_name: 'active', active: 'contributors' %>

  <div class='col-lg-9 col-md-9 col-sm-9 col-xs-9 custom-tab'>
    <div class='custom-tab-content active'>
      <div class='tab-content-header'>
        <h3 class='heading-3'>Edit contributor</h3>

        <div class='pull-right'>
          <%= link_to contributors_project_path(@project), class: 'btn btn-primary' do %>
              <span class='glyphicon glyphicon-arrow-left'></span>
              Back
          <% end %>
        </div>
      </div>

      <hr>
      <div class="col-md-12 mg-b10">
        <%= render 'contributions/form' %>
      </div>
    </div>
  </div>
</div>

app/views/contributions/index.html.erb
<h2>Contributions</h2>
<div class="col-md-8">
  <%= render 'contributions/list' %>
</div>

app/views/contributions/new.html.erb
<h2>Contributions</h2>
<div class="col-md-8">
  <%= render 'contributions/list' %>
</div>

<div class="col-md-4">
  <%= render 'contributions/form' %>
</div>